// Barrel re-export. Per-resource modules are co-located in this directory; this
// file exists so existing `import { foo } from '@/api/client'` callsites keep
// working. New code may import directly from the per-resource module.

export * from './_fetch'
export * from './storage'
export * from './probes'
export * from './outlets'
export * from './programs'
export * from './feed'
export * from './system'
export * from './alerts'
export * from './tokens'
export * from './notifications'
export * from './backups'
export * from './devices'
export * from './dashboard'
export * from './measurements'
export * from './livestock'
export * from './tank'
export * from './journal'
export * from './prompts'
export * from './events'
export * from './agent'
export * from './dosing'
export * from './maintenance'
